### PR TITLE
#29: fix a typo

### PR DESCRIPTION
**Pull request by timotheeMM**
I solved the issue #29!
Do not hesitate to tell me if I have to modify something else... 😊

### CODE REVIEW

**Comment by paithiov909** [comment]
@timotheeMM
Please regenerate and update the Rd files.

**Comment by timotheeMM** [comment]
Hello @paithiov909,
Sorry but I don't understand what you want me to do.

**Comment by paithiov909** [comment]
@timotheeMM I'm not your tutor, nor GitHub copilot. If you have any problems developing R packages, read other useful resources like [this book](https://r-pkgs.org/). Note that this package depends on 'Rcpp' and requires C++ build tools to run `devtools::document`.

Can you fix the issue by the weekend? If it is too difficult for you, I will close this PR and fix that by myself.

**Comment by timotheeMM** [comment]
Hi @paithiov909,
I thought that PR was just a typo fix, but it's actually more complicated than that. I don't have the tools or skills to do it.
So you can close this PR.
Thanks.

**Pull request closed without merging**
